from django.db import models
from django.urls import reverse
from netbox.models import NetBoxModel

class CustomPage(NetBoxModel):
    """
    Main model to store custom web pages created by users.
    """
    name = models.CharField(
        max_length=100, 
        unique=True,
        verbose_name="Page Name"
    )
    slug = models.SlugField(
        max_length=100, 
        unique=True,
        help_text="Unique URL-friendly identifier (e.g., 'my-status-page')"
    )
    # Stores the HTML layout generated by Quill.js
    content_html = models.TextField(
        blank=True,
        verbose_name="HTML Content"
    )
    # Stores the JavaScript logic (API Calls) edited by Monaco Editor
    content_js = models.TextField(
        blank=True,
        verbose_name="JavaScript Logic"
    )
    # Stores custom CSS styles
    content_css = models.TextField(
        blank=True,
        verbose_name="CSS Styles"
    )

    class Meta:
        ordering = ('name',)
        verbose_name = 'Custom Page'
        verbose_name_plural = 'Custom Pages'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # Links the model to the detail view defined in urls.py
        return reverse('plugins:netbox_custom_pages:custompage', args=[self.slug])